name: Deploy GovoStage
on:
  push:
    branches: [ main ] # Change en 'main' si c'est le nom de ta branche sur GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et d√©ploiement
        uses: appleboy/ssh-action@master
        with:
          host: 46.224.42.239
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/govostage
            git pull origin master
            cd backend
            npm install
            npm run build
            pm2 reload govostage-backend